### ISSUE TITLE
Implement proxy support

### ISSUE THREAD

**Issue by MrRefactoring** [MrRefactoring/jira-api-wrapper#20]
It is necessary to analyze whether there is a need to implement `proxy` support for the `Jira API`. And how to do it correctly. I also do not have the capacity to test this.

**Comment by MrRefactoring** [comment]
I created a test version of the proxy implementation. Now you need to test it.

Please install the package using the following method: `npm i git+https://github.com/MrRefactoring/jira-api-wrapper.git#features/proxy`

Use the following code, where ca is your ssl certificate:
```javascript
var jira = new jiraClient({
  host: 'jira-host.com',
  port: '8443',
  basic_auth: {
    base64: base64Str
  },
  ca: fs.readFileSync(caFile)
});
```

Perhaps should also add `cert` and `key` to the initial setup. Write what the result of the library is now

**Comment by gioboa** [comment]
Hi @MrRefactoring ,
did you have some feedback for this feature?

**Comment by MrRefactoring** [comment]
Hi, @gioboa, I'm still waiting feedback for this feature. I can not check it myself :(

**Comment by gioboa** [comment]
I've got this [issue](https://github.com/gioboa/jira-plugin/issues/90) in my plugin.
I think is the same situation. I thought was VsCode issue but now I think is a lib issue.
What do you think?

**Comment by MrRefactoring** [comment]
> I've got this [issue](https://github.com/gioboa/jira-plugin/issues/90) in my plugin.
> I think is the same situation. I thought was VsCode issue but now I think is a lib issue.
> What do you think?
> 
> **UPDATE**
> 
> I looked at your code and I saw that the _magic_ is done by `ca` property.
> I can implement the solution in my code and get a feedback from users.

This would be ideal. I also thought about it. I am now synchronizing this branch with the master. And you can try

**Comment by MrRefactoring** [comment]
@gioboa, updated branch, added `cert` and `key`, if suddenly, it is also necessary. You can try to implement this at your plugin.

**Comment by gioboa** [comment]
Thanks.
I was looking inside request lib and `cert` and `key` , as you say, seems are necessaries.

**Comment by gioboa** [comment]
The solution didn't work for my issue maybe wrap certificates properties into agentOptions can be the solution.
I found this solution [here](https://github.com/request/request#using-optionsagentoptions) 😞

**Comment by MrRefactoring** [comment]
Do you mean that you need to use agentOption and it will work?

**Comment by gioboa** [comment]
I'm not sure because I don't have the environment for test the solution. I'm waiting for feedback.
Request lib docs explain to use agentOptions so I hope is the solution.

**Comment by MrRefactoring** [comment]
Well, then we wait. I will make a request to the repository with the library after a while

**Comment by MrRefactoring** [comment]
@gioboa, I noticed that you closed the issue in your project. As I understand it, the problem was solved, could you help me also complete my issue here?

**Comment by gioboa** [comment]
Yes, I was promise myself to update you.
The solution was adding strictSSL = false in the request without any agentOptions, CA, cert and key.
With this flag to false, under the hood, request lib set rejectUnauthorized flag to false in the request.
strictSSL is like an alias for rejectUnauthorized.

**Comment by MrRefactoring** [comment]
> Yes, I was promise myself to update you.
> The solution was adding strictSSL = false in the request without any agentOptions, CA, cert and key.
> With this flag to false, under the hood, request lib set rejectUnauthorized flag to false in the request.
> strictSSL is like an alias for rejectUnauthorized.

And how do you manage without the cert.pem file?

**Comment by gioboa** [comment]
I suppose you don't need pem file with this flag.
Every https has own certificate and nobody before yesterday complain about this issue. I think the problem was that this user have self signed cert.

**Comment by MrRefactoring** [comment]
Hmm, well, thanks for the help. I think to leave the `cert`, `key`, `ca` and use strictSSL = false

**Comment by gioboa** [comment]
My user in the first test use agentOptions and strictSSL and the request fail. Only with strictSSL the request works great.

**Comment by MrRefactoring** [comment]
@gioboa, what do you think about this code? Maybe we need to implement this?

```javascript
var req = https.request({ 
      host: '192.168.1.1', 
      port: 443,
      path: '/',
      ca: [fs.readFileSync([certificate path], {encoding: 'utf-8'})], // Attention
      method: 'GET',
      rejectUnauthorized: true, // Attention
      requestCert: true,  // Attention
      agent: false
}
```

**Comment by gioboa** [comment]
request lib don't set rejectUnauthorized for normal request, but only if you force strictSSL.
From request docs: 
`Note: to use your own certificate authority, you need to specify an _agent_ that was created with that CA as an option.`
Have a look at [this](https://medium.com/nodejs-tips/ssl-certificate-explained-fc86f8aa43d4) article.
I solved the problem only testing step by step.
Did you open an issue to request lib for get info?

**Comment by MrRefactoring** [comment]
Sorry for not answering for so long. No, I did not ask a question to the request library. I looked at your changes and looked on the Internet, it seems you are right. Thanks for the help
