### ISSUE TITLE
getAuthorizeURL Error

### ISSUE THREAD

**Issue by 91debug** [MrRefactoring/jira-api-wrapper#30]
```javascript
JiraApi.getAuthorizeURL(
      {
        host: 'xxx.atlassian.net',
        port: 443,
        oauth: {
          consumerKey: 'iw_contact',
          privateKey: `-----BEGIN RSA PRIVATE KEY-----
          private
          -----END RSA PRIVATE KEY-----`,
        },
      },
      (error: any, oauth: any) => {
        console.log(oauth);
      }
    );
```

i want to get Oauth url

![image](https://user-images.githubusercontent.com/7323747/53282849-f8249780-3780-11e9-8d30-dd69d9c6c8ff.png)

but failed

**Comment by MrRefactoring** [comment]
I updated the library to version 0.5.1, where I fixed this bug, please test the new version.

Thanks so much for making my library better. Your help is very important to me.
